### ISSUE TITLE
User Story 25: As a buyer, user can post reviews about the product they bought

### ISSUE THREAD

**Issue by Megha255** [COMP231-S4G4/OneStopShop#100]
User Story 25: As a buyer, user can post reviews about the product they bought

- [ ]  #155 Task 25.1: Create Reviews database

- [ ]  #156 Task 25,2: Code add review section and write query to add review to the database

- [ ]  #157 Task 25.3: Document the Review Functionality

**Comment by Megha255** [comment]
Story Fails
