### ISSUE TITLE
User Story 27:  As a buyer, user can search for the product amongst the list of products using keywords

### ISSUE THREAD

**Issue by Megha255** [COMP231-S4G4/OneStopShop#102]
User Story 27: As a buyer, user can see the search results for their item search

- [x]  #161 Task 27.1: Design and code search screen

- [x]  #162 Task 27.2: Write query to fetch search results for searches

- [ ]  #163 Task 27.3: Document search functionality
