### ISSUE TITLE
User Story 28: As a seller, user can have customized-Order List that has all the customized orders  

### ISSUE THREAD

**Issue by Megha255** [COMP231-S4G4/OneStopShop#103]
User Story 28: As a seller, user can have customized-Order List that has all the customized orders  

- [x] #164 Task 28.1: Design Customized Order List

- [x]  #165 Task 28.2: Create table for Customized Orders

- [ ]  #166 Task 28.3: Code and write query to fetch the customized orders

- [ ]  #167 Task 28.4: Document Customized Orders Functionality for sellers
