### ISSUE TITLE
User Story 30: As a buyer, user can fill Custom-Tailored Product form to place order for customized product

### ISSUE THREAD

**Issue by Megha255** [COMP231-S4G4/OneStopShop#105]
User Story 30: As a buyer, user can fill Custom-Tailored Product form to place order for customized product

- [x]  #170 Task 30.1: Design Customized Order Form

- [x]  #171 Task 30.2: Code and write query to add the customized order form details to the database
 
- [ ]  #172 Task 30.3: Document fill the Customized Order form for the buyers
