### ISSUE TITLE
User Story 31: As a buyer, user can add product to the Wishlist

### ISSUE THREAD

**Issue by Megha255** [COMP231-S4G4/OneStopShop#106]
User Story 31: As a buyer, user can add product to the Wishlist

- [x]  #173 Task 31.1: Create database table for Wishlist

- [x]  #174 Task 31.2: Code and write query to add products to Wishlist

- [ ]  #175 Task 31.3: Document Wishlist for buyers in the guide
