### ISSUE TITLE
User Story 32: As a buyer, user can view the items in the Wishlist

### ISSUE THREAD

**Issue by Megha255** [COMP231-S4G4/OneStopShop#107]
User Story 32: As a buyer, user can view the items in the Wishlist

- [x]  #176 Task 32.1: Design Wishlist Screen

- [x]  #177 Task 32.2: Code and write query to fetch the items in the Wishlist from database

- [x]  #178 Task 32.3: Code to make edits in the Wishlist
