### ISSUE TITLE
User Story 33: As a buyer, user can see their Account Information they added while registration

### ISSUE THREAD

**Issue by Megha255** [COMP231-S4G4/OneStopShop#108]
User Story 33: As a buyer, user can see their Account Information they added while registration

- [x]  #179 Task 33.1: Design Profile Screen

- [x]  #180 Task 33.2: Code and write query to fetch all the account information of buyers from database

- [ ]  #181 Task 33.3: Code to edit Account Information
