### ISSUE TITLE
User Story 34: As a buyer, user can see all the orders placed previously and recently

### ISSUE THREAD

**Issue by Megha255** [COMP231-S4G4/OneStopShop#109]
User Story 34: As a buyer, user can see all the orders placed previously and recently

- [x]  #182 Task 34.1: Design Previous Orders Screen

- [x]  #183 Task 34.2: Code and fetch order previously placed by a buyer from the database

- [ ]  #184 Task 34.3: Document the previous order feature
