### ISSUE TITLE
User Story 35: User can Login to the application with valid credentials

### ISSUE THREAD

**Issue by Megha255** [COMP231-S4G4/OneStopShop#110]
User Story 35: User can Login to the application with valid credentials

- [x]  #185 Task 35.1: Design Login Screen

- [x]  #186 Task 35.2: Create Login/Registration table in the database

- [x]  #187 Task 35.3:  Code and write query to authenticate user login credentials
