### ISSUE TITLE
User Story 36: User can register themselves after they fill out all the necessary details

### ISSUE THREAD

**Issue by Megha255** [COMP231-S4G4/OneStopShop#111]
User Story 36: User can register themselves after they fill out all the necessary details

- [x]  #188 Task 36.1: Design Registration Screen

- [x]  #189 Task 36.2: Code and write query to add the registration information in the database

- [x]  #190 Task 36.3: Document Registration functionality
