### ISSUE TITLE
User Story 19:  As a seller, user can add blog

### ISSUE THREAD

**Issue by Megha255** [COMP231-S4G4/OneStopShop#94]
User Story 19:  As a seller, user can add blog

- [x] #138 Task 19.1: Design the Blogs Screen

- [x]  #139 Task 19.2: Code and write query to fetch blogs from database

- [x] #140 Task 19.3: Document Blog section
