### ISSUE TITLE
User Story 20: As a seller, user can delete blog

### ISSUE THREAD

**Issue by Megha255** [COMP231-S4G4/OneStopShop#95]
User Story 20: As a seller, user can delete blog

- [x]  #141 Task 20.1: Design delete dialog box

- [x]  #142 Task 20.2: Write the code for delete blog and query to update the database

- [x]  #143 Task 20.3: Document the Delete Blog Functionality
