### ISSUE TITLE
User Story 21: As a seller, user can edit blog

### ISSUE THREAD

**Issue by Megha255** [COMP231-S4G4/OneStopShop#96]
User Story 21: As a seller, user can edit blog

- [x]  #144 Task 21.1: Design Edit Blog screen

- [x]  #145 Task 21.2: Code the screen and query to update the database

- [x]  #146 Task 21.3: Document the Edit Blog Functionality
