### ISSUE TITLE
User Story 23: As a buyer, user can read blogs for better shopping insights from their sellers.

### ISSUE THREAD

**Issue by Megha255** [COMP231-S4G4/OneStopShop#98]
User Story 23: As a buyer, user can read blogs for better shopping insights from their sellers.

- [x]  #149 Task 23.1: Design the Blogs Screen

- [x]  #150 Task 23.2: Code and write query to fetch blogs from database

- [x]  #151 Task 23.3: Document Blog section
