### ISSUE TITLE
User Story 24: As a seller, user can have list of subscribers for the store for better customer engagement

### ISSUE THREAD

**Issue by Megha255** [COMP231-S4G4/OneStopShop#99]
User Story 24: As a seller, user can have list of subscribers for the store for better customer engagement

- [x]  #152 Task 24.1: Design the table and code Subscribers List Screen

- [x]  #153 Task 24.2: Create table for Subscribers and write query to fetch subscribers list from database

- [ ]  #154 Task 24.3: Document Subscribers Functionality for seller
